name: Deploy Firebase

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./functions
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install firebase-tools
        run: npm install -g firebase-tools
      - run: cd functions && pnpm ci
      #- run: cd functions && npm run test
      - name: Deploy to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" -P "${{ secrets.FIREBASE_PROJECT }}" --force
